server:
  port: 8086

spring:
  application:
    name: coffee-order
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: kosa01
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.sql: debug


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
